[2023-02-18 05:04:25,354] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:04:26,170] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:04:26,171] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:04:26,172] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-02-18 05:04:26,172] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:04:28,445] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): also_run_this> on 2023-02-17T00:00:00+00:00
[2023-02-18 05:04:28,685] {standard_task_runner.py:52} INFO - Started process 2943 to run task
[2023-02-18 05:04:33,815] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2023-02-17T00:00:00+00:00', '--job-id', '3188', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp8g2k0zfa', '--error-file', '/tmp/tmp67pwa2rz']
[2023-02-18 05:04:35,432] {standard_task_runner.py:77} INFO - Job 3188: Subtask also_run_this
[2023-02-18 05:04:50,200] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.also_run_this 2023-02-17T00:00:00+00:00 [running]> on host a39de0034eff
[2023-02-18 05:05:07,236] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2023-02-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-17T00:00:00+00:00
[2023-02-18 05:05:08,096] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-02-18 05:05:09,452] {bash.py:158} INFO - Running command: echo "run_id=scheduled__2023-02-17T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2023-02-17 00:00:00+00:00: scheduled__2023-02-17T00:00:00+00:00, externally triggered: False>"
[2023-02-18 05:05:11,598] {bash.py:169} INFO - Output:
[2023-02-18 05:05:18,451] {bash.py:173} INFO - run_id=scheduled__2023-02-17T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2023-02-17 00:00:00+00:00: scheduled__2023-02-17T00:00:00+00:00, externally triggered: False>
[2023-02-18 05:05:18,611] {bash.py:177} INFO - Command exited with return code 0
[2023-02-18 05:05:27,974] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20230217T000000, start_date=20230218T050425, end_date=20230218T050527
[2023-02-18 05:05:34,943] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-02-18 05:05:38,215] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2943
[2023-02-18 05:06:31,356] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-18 05:06:31,357] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-02-18 05:06:31,675] {process_utils.py:66} INFO - Process psutil.Process(pid=2943, status='terminated', exitcode=1, started='05:04:28') (2943) terminated with exit code 1
