[2023-02-18 05:06:53,736] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:06:53,789] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:06:53,789] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:06:53,790] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-02-18 05:06:53,791] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:06:54,030] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2023-02-17T00:00:00+00:00
[2023-02-18 05:06:54,139] {standard_task_runner.py:52} INFO - Started process 3085 to run task
[2023-02-18 05:06:54,145] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2023-02-17T00:00:00+00:00', '--job-id', '3192', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpvl3goot5', '--error-file', '/tmp/tmp4iqlu4xp']
[2023-02-18 05:06:54,150] {standard_task_runner.py:77} INFO - Job 3192: Subtask run_after_loop
[2023-02-18 05:06:54,228] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2023-02-17T00:00:00+00:00 [running]> on host a39de0034eff
[2023-02-18 05:06:54,386] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2023-02-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-17T00:00:00+00:00
[2023-02-18 05:06:54,388] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-02-18 05:06:54,534] {bash.py:158} INFO - Running command: echo 1
[2023-02-18 05:06:54,714] {bash.py:169} INFO - Output:
[2023-02-18 05:06:54,724] {bash.py:173} INFO - 1
[2023-02-18 05:06:54,725] {bash.py:177} INFO - Command exited with return code 0
[2023-02-18 05:06:54,771] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20230217T000000, start_date=20230218T050653, end_date=20230218T050654
[2023-02-18 05:06:55,293] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-18 05:06:55,320] {local_task_job.py:146} INFO - Task exited with return code 0
