[2023-02-17 08:34:03,694] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_branch_dop_operator_v3.condition 2023-02-15T00:21:00+00:00 [queued]>
[2023-02-17 08:34:03,796] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_branch_dop_operator_v3.condition 2023-02-15T00:21:00+00:00 [queued]>
[2023-02-17 08:34:03,796] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-02-17 08:34:03,797] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-02-17 08:34:03,798] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-02-17 08:34:03,823] {taskinstance.py:1063} INFO - Executing <Task(BranchPythonOperator): condition> on 2023-02-15T00:21:00+00:00
[2023-02-17 08:34:03,829] {standard_task_runner.py:52} INFO - Started process 1650 to run task
[2023-02-17 08:34:03,838] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_branch_dop_operator_v3', 'condition', '2023-02-15T00:21:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_branch_python_dop_operator_3.py', '--cfg-path', '/tmp/tmp_wnm1ywh', '--error-file', '/tmp/tmpbrfq_d6w']
[2023-02-17 08:34:03,844] {standard_task_runner.py:77} INFO - Job 38: Subtask condition
[2023-02-17 08:34:03,958] {logging_mixin.py:104} INFO - Running <TaskInstance: example_branch_dop_operator_v3.condition 2023-02-15T00:21:00+00:00 [running]> on host a39de0034eff
[2023-02-17 08:34:04,068] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_branch_dop_operator_v3
AIRFLOW_CTX_TASK_ID=condition
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T00:21:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-15T00:21:00+00:00
[2023-02-17 08:34:04,073] {logging_mixin.py:104} INFO - ------------- exec dttm = 2023-02-15T00:21:00+00:00 and minute = 21
[2023-02-17 08:34:04,074] {python.py:118} INFO - Done. Returned value was: dummy_task_2
[2023-02-17 08:34:04,075] {skipmixin.py:124} INFO - Following branch dummy_task_2
[2023-02-17 08:34:04,090] {skipmixin.py:155} INFO - Skipping tasks ['dummy_task_1']
[2023-02-17 08:34:04,189] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_branch_dop_operator_v3, task_id=condition, execution_date=20230215T002100, start_date=20230217T083403, end_date=20230217T083404
[2023-02-17 08:34:08,910] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-02-17 08:34:08,992] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 1650
[2023-02-17 08:34:09,848] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-17 08:34:09,891] {process_utils.py:66} INFO - Process psutil.Process(pid=1650, status='terminated', exitcode=1, started='08:34:03') (1650) terminated with exit code 1
